version: '3'
services:
  auction_django_gunicorn:
    build: .
    volumes:
      - static_volume:/var/www/auction-private/static:rw
      - media_volume:/var/www/auction-private/media:rw
      - ./db:/app/db:rw
    env_file:
      - ./.env
    expose:
      - "8001"
    restart: always

  auction_memcached:
    image: memcached:alpine
    ports:
      - "11214:11214"
    command:
      - '-m 128'

volumes:
  static_volume:
  media_volume:
