# Generated by Django 4.1.4 on 2023-04-18 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 21, 14, 43, 945922)),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='startBid',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidValue',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
