# Generated by Django 4.1.4 on 2023-04-18 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlisting_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 21, 25, 5, 444455)),
        ),
    ]
