# Generated by Django 4.2.4 on 2023-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0017_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_text", models.TextField()),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
            ],
        ),
    ]
