# Generated by Django 4.2.4 on 2023-08-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0018_footercontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("font_size", models.PositiveIntegerField(default=16)),
                ("font_color", models.CharField(default="#000000", max_length=7)),
                (
                    "font_style",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("italic", "Italic"),
                            ("bold", "Bold"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerLogo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="partners/")),
                ("alt_text", models.CharField(max_length=255)),
                ("width", models.PositiveIntegerField(default=100)),
                ("height", models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name="FooterContent",
        ),
    ]
