# Generated by Django 4.2.4 on 2023-08-14 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0019_announcement_partnerlogo_delete_footercontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
