# Generated by Django 4.2.4 on 2023-08-14 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0020_alter_announcement_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="font_color",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="font_size",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="font_style",
        ),
    ]
